/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.sleepydragon.capbutnbrightness.clib;

public interface CLibConstants {
  public final static int EACCES = CLibJNI.EACCES_get();
  public final static int EBADF = CLibJNI.EBADF_get();
  public final static int EFAULT = CLibJNI.EFAULT_get();
  public final static int ELOOP = CLibJNI.ELOOP_get();
  public final static int ENAMETOOLONG = CLibJNI.ENAMETOOLONG_get();
  public final static int ENOENT = CLibJNI.ENOENT_get();
  public final static int ENOMEM = CLibJNI.ENOMEM_get();
  public final static int ENOTDIR = CLibJNI.ENOTDIR_get();
  public final static int EOVERFLOW = CLibJNI.EOVERFLOW_get();
}
